# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            TekDesk
tagline:          'The talkdesk tech blog'
description:      'The <a href="http://talkdesk.com" target="_blank">talkdesk</a> tech blog.'
url:              http://joaoptrindade.com/hyde/
baseurl:          /hyde/

author:
  name:           'Joao Trindade'
  url:            https://twitter.com/joaotrindade

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://joninvski.com/hyde
